- name: Install NVM
  when: INSTALL_NVM | bool
  changed_when: false
  shell:
    cmd: |
      export NVM_DIR="$HOME/.nvm" && (
        git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
        cd "$NVM_DIR"
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
      ) && \. "$NVM_DIR/install.sh"
  args:
    executable: /bin/bash
    warn: true
