- name: Download pyenv-installer
  become: true
  ansible.builtin.get_url:
    url: https://raw.github.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest: "{{ OE_HOME }}/pyenv-installer.sh"
    mode: 755

- name: Install PYENV
  when: INSTALL_PYENV | bool
  changed_when: false
  shell:
    cmd: |
      {{ OE_HOME }}/pyenv-installer.sh
      sed -Ei -e '/^([^#]|$)/ {a \
      export PYENV_ROOT="{{ OE_HOME }}/.pyenv"
      a \
      export PATH="$PYENV_ROOT/bin:$PATH"
      a \
          ' -e ':a' -e '$!{n;ba};}' {{ OE_HOME }}/.profile
          echo 'eval "$(pyenv init --path)"' >>{{ OE_HOME }}/.profile
          echo 'eval "$(pyenv init -)"' >> {{ OE_HOME }}/.bashrc
  args:
    executable: /bin/bash
    warn: true
