- name: Blockinfile
  when: CONFIG_BASHRC_COLOR  | bool
  blockinfile:
    path: "{{ OE_HOME }}/.bashrc"
    marker: "# {mark} BASHRC_COLOR"
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e "/^[^*]/d" -e "s/* \(.*\)/ (\1)/"
      }
      export PS1="\[\033[01;32m\]\u@\h\[\e[91m\]\$(parse_git_branch) \[\e[1;33m\]\$(date +'%Y/%m/%d') \t\[\033[00m\]:\n\[\e[34m\]\w\[\e[00m\]$ "
