- name: Remove Old Yarn
  when: INSTALL_YARN | bool
  apt:
    name: yarn
    state: absent

- name: Ensure apt-transport-https is installed
  when: INSTALL_YARN | bool
  apt:
    name: apt-transport-https

- name: Add Yarn apt key
  when: INSTALL_YARN | bool
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  when: INSTALL_YARN | bool
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install Yarn
  when: INSTALL_YARN | bool
  apt:
    name: yarn
    state: present
