galaxy_info:
  role_name: fzf
  author: Poliyka
  description: Ansible role for fzf
  license: MIT
  min_ansible_version: 2.13.3

  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
    - fzf
    - debian
    - ubuntu

dependencies:
  - git

