- name: Install FZF
  when: INSTALL_FZF | bool
  changed_when: false
  shell:
    cmd: |
      git clone --depth 1 https://github.com/junegunn/fzf.git {{ OE_HOME }}/.fzf
      {{ OE_HOME }}/.fzf/install
  args:
    executable: /bin/bash
    warn: true
