- name: Install dependent library
  when: INSTALL_DEPENDENT | bool
  become: true
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    update_cache: true
  loop:
    # Python
    - python3-venv
    - python3-wheel
    - python3-setuptools
    - python3-virtualenv
    - python3-dev
    - python3-pip
    - python-openssl
    # Lib
    - libxslt-dev
    - libzip-dev
    - libldap2-dev
    - libsasl2-dev
    - libjpeg-dev
    - gdebi
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg62-dev
    - node-less
    # Tools
    - git
    - wget
    - make
    - curl
    - vim
    - neovim
    - trash-cli
    - vim-gtk3
    - pipenv
    - silversearcher-ag
    - exuberant-ctags
    - figlet
    - tox
    - net-tools
    - htop
    - cargo
